apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-processing
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/docker/data_processing